/*
- 2022년 1월의 도서 판매 데이터 기준
- 저자 별, 카테고리 별 매출액(TOTAL_SALES = 판매량 * 판매가) 구하기
- 저자 ID(AUTHOR_ID), 저자명(AUTHOR_NAME), 카테고리(CATEGORY), 매출액(SALES) 출력
- 저자 ID 오름차순, 카테고리 내림차순
*/
SELECT a.AUTHOR_ID, a.AUTHOR_NAME, b.CATEGORY
    , SUM(s.SALES * b.PRICE) AS TOTAL_SALES
FROM BOOK b 
INNER JOIN BOOK_SALES s ON b.BOOK_ID = s.BOOK_ID
INNER JOIN AUTHOR a ON b.AUTHOR_ID = a.AUTHOR_ID
WHERE s.SALES_DATE LIKE '2022-01%'
GROUP BY a.AUTHOR_ID, b.CATEGORY
ORDER BY a.AUTHOR_ID, b.CATEGORY DESC;