SELECT PRODUCT_CODE
        , (SUM(SALES_AMOUNT) * PRICE) AS SALES
FROM PRODUCT p LEFT JOIN OFFLINE_SALE o
    ON p.PRODUCT_ID = o.PRODUCT_ID
-- 판매량이 0인 상품 존재
WHERE SALES_AMOUNT IS NOT NULL
GROUP BY p.PRODUCT_CODE
ORDER BY SALES DESC, PRODUCT_CODE;