/*
- FOOD_TYPE별 FAVORITES 수가 가장 많은 식당
- 음식 종류, ID, 식당 이름, 즐겨찾기수를 조회
- 음식 종류를 기준으로 내림차순
*/
# SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
# FROM REST_INFO
# WHERE (REST_ID, FAVORITES) IN (
#     SELECT REST_ID, MAX(FAVORITES)
#     FROM REST_INFO
#     GROUP BY FOOD_TYPE
# )
# ORDER BY FOOD_TYPE DESC;
WITH w1 AS (
    SELECT REST_ID
            , RANK() OVER(PARTITION BY FOOD_TYPE ORDER BY FAVORITES DESC) AS ranking
    FROM REST_INFO
)
SELECT i.FOOD_TYPE, i.REST_ID, i.REST_NAME, i.FAVORITES
FROM REST_INFO i INNER JOIN w1
ON i.REST_ID = w1.REST_ID
WHERE w1.ranking = 1
ORDER BY i.FOOD_TYPE DESC;