WITH RECURSIVE CTE AS (
    SELECT 0 AS NUM
    UNION ALL
    SELECT NUM+1
    FROM CTE
    WHERE NUM < 23
)
SELECT c.NUM AS HOUR, COUNT(a.ANIMAL_ID) AS COUNT
FROM CTE c LEFT JOIN ANIMAL_OUTS a
        ON c.NUM = HOUR(a.DATETIME)
GROUP BY c.NUM
ORDER BY c.NUM;