SELECT i.ANIMAL_ID, i.NAME
FROM ANIMAL_INS i JOIN ANIMAL_OUTS o 
                    ON i.ANIMAL_ID = o.ANIMAL_ID
-- i.DATETIME : 보호시작일, o.DATETIME : 입양일
WHERE i.DATETIME >= o.DATETIME
ORDER BY i.DATETIME;