SELECT FIRST_HALF.FLAVOR
FROM FIRST_HALF 
    INNER JOIN ICECREAM_INFO 
    ON FIRST_HALF.FLAVOR = ICECREAM_INFO.FLAVOR
WHERE 1=1
    AND ICECREAM_INFO.INGREDIENT_TYPE = 'fruit_based' 
    AND FIRST_HALF.TOTAL_ORDER >= 3000
ORDER BY TOTAL_ORDER DESC;