WITH w1 AS (
    SELECT *, RANK() OVER(PARTITION BY CATEGORY ORDER BY PRICE DESC) AS max_price
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
)
SELECT f.CATEGORY, f.PRICE AS MAX_PRICE, f.PRODUCT_NAME
FROM FOOD_PRODUCT f INNER JOIN w1
ON f.PRODUCT_ID = w1.PRODUCT_ID
WHERE w1.max_price = 1
ORDER BY f.PRICE DESC;